openapi: 3.0.1
info:
  title: monster-planetar
  x-cortex-tag: monster-planetar
  x-cortex-custom-metadata:
    alignment: chaotic-evil
    type: elemental
    challenge_rating: 29
    legendary: false
    armor_class: 13
    hit_points: 284
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-planetar
      alias: github-token-test
